from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

from models.enums import CasePriority, ConfidenceLevel, RiskLevel, DraftType


def score_to_confidence_level(score: float) -> ConfidenceLevel:
    """
    Map raw numerical confidence score (0.00 - 1.00) to user-facing ConfidenceLevel enum.
    Thresholds defined per SRS §5.13:
      - Low:      0.00 – 0.49
      - Moderate: 0.50 – 0.79
      - High:     0.80 – 1.00
    """
    if score >= 0.80:
        return ConfidenceLevel.HIGH
    elif score >= 0.50:
        return ConfidenceLevel.MODERATE
    return ConfidenceLevel.LOW


class AITriageData(BaseModel):
    """Structured result returned from AI Case Triage per SRS §5.2."""
    suggested_category: Optional[str] = Field(default=None, description="Suggested IT category (e.g. Network, Hardware, Access)")
    suggested_severity: Optional[str] = Field(default=None, description="Suggested severity (e.g. Critical, High, Medium, Low)")
    suggested_priority: Optional[CasePriority] = Field(default=CasePriority.P3, description="Recommended SLA priority (p1-p4)")
    confidence_score: float = Field(default=0.75, ge=0.0, le=1.0, description="Internal raw confidence score")
    confidence_level: ConfidenceLevel = Field(default=ConfidenceLevel.MODERATE, description="Enum displayed to user")
    supporting_factors: List[str] = Field(default_factory=list, description="Reasons for triage classification")
    missing_info: List[str] = Field(default_factory=list, description="Missing details operator should request")
    suggested_team_name: Optional[str] = Field(default=None, description="Suggested team name or specialization")
    recommended_next_action: Optional[str] = Field(default=None, description="Immediate recommended next step")


class CaseRiskData(BaseModel):
    """Structured result returned from Case Risk Evaluation per SRS §5.7."""
    risk_level: RiskLevel = Field(default=RiskLevel.LOW, description="Low, Moderate, High, Critical")
    risk_score: float = Field(default=0.1, ge=0.0, le=1.0, description="Internal composite risk score")
    signals: Dict[str, Any] = Field(default_factory=dict, description="Identified risk factors and signals")
    rationale: str = Field(default="", description="Human-readable explanation of risk level")


class AIDraftData(BaseModel):
    """Structured communication draft generated by AI per SRS §5.9."""
    draft_type: DraftType = Field(description="info_request | progress_update | resolution | escalation_summary")
    subject: Optional[str] = Field(default=None, description="Optional subject line")
    body: str = Field(description="Draft text for human operator review")


class AIProvider(ABC):
    """Abstract interface for AI Providers supporting Google Gemini and deterministic mocks."""

    @abstractmethod
    async def triage_case(
        self,
        title: str,
        description: str,
        context: Optional[Dict[str, Any]] = None,
    ) -> AITriageData:
        """Analyze case title and description to produce category, priority, and missing info recommendations."""
        pass

    @abstractmethod
    async def summarize_case(
        self,
        title: str,
        history_text: str,
        new_message_text: str,
    ) -> str:
        """Recompute living case summary incorporating history and latest message."""
        pass

    @abstractmethod
    async def assess_risk(
        self,
        case_context: Dict[str, Any],
    ) -> CaseRiskData:
        """Evaluate case signals and SLA context to assess escalation risk."""
        pass

    @abstractmethod
    async def draft_communication(
        self,
        draft_type: DraftType,
        case_context: Dict[str, Any],
        custom_instructions: Optional[str] = None,
    ) -> AIDraftData:
        """Generate draft communication for operator review."""
        pass
